success:
  recordCreated:
    status: success
    api-message: "New %s created successfully"
    message: "New %s created successfully"
  recordUpdated:
    status: success
    api-message: "%s updated successfully"
    message: "%s updated successfully"
  recordDeleted:
    status: success
    api-message: "%s deleted successfully"
    message: "%s deleted successfully"  
error:    
  userNameExist:
    code: 200089
    api-message: 'User Name already exist'
    message: 'User Name already exist'  